# Generated by Django 2.0.6 on 2018-07-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/'),
        ),
    ]
